{% set name = "ldas-tools-diskcacheAPI-swig" %}
{% set version = "2.6.8" %}

# dependencies
{% set ldas_tools_cmake_version = "1.0.8" %}
{% set ldas_tools_diskcacheapi_version = "2.7.0" %}
{% set ldas_tools_ldasgen_swig_version = "2.6.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz"
  sha256: 187c5cc3630e8fb0fb615212dddba5e6131aba44637529b15563153fcdfe3391

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - pkg-config  # [unix]
  host:
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - ldas-tools-diskcacheapi {{ ldas_tools_diskcacheapi_version }}
    - swig >=3.0.7,<4.0.0a0
  run:
    - ldas-tools-diskcacheapi >={{ ldas_tools_diskcacheapi_version }}

test:
  commands:
    - test -f ${PREFIX}/include/diskcacheAPI/diskCache.i  # [unix]

outputs:
  - name: ldas-tools-diskcacheapi-swig

  - name: python-ldas-tools-diskcacheapi
    script: install-python.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake >=3.6
        - pkg-config  # [unix]
      host:
        - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
        - ldas-tools-diskcacheapi {{ ldas_tools_diskcacheapi_version }}
        - {{ pin_subpackage('ldas-tools-diskcacheapi-swig', exact=True) }}
        - python
        - python-ldas-tools-ldasgen >={{ ldas_tools_ldasgen_swig_version }}
        - swig >=3.0.7,<4.0.0a0
      run:
        - python
        - python-ldas-tools-al
        - ldas-tools-diskcacheapi >={{ ldas_tools_diskcacheapi_version }}
        - {{ pin_subpackage('ldas-tools-diskcacheapi-swig', exact=True) }}
        - python-ldas-tools-ldasgen >={{ ldas_tools_ldasgen_swig_version }}
    test:
      imports:
        - LDAStools.diskCache
    about:
      home: https://wiki.ligo.org/Computing/LDASTools
      dev_url: https://git.ligo.org/ldastools/LDAS_Tools
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: Python bindings for the LDAS Tools disk cache library

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: SWIG interface for the LDAS Tools disk cache library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
