{% set name = "ldas-tools-diskcacheAPI-swig" %}
{% set version = "2.6.12" %}

# dependencies
{% set ldas_tools_cmake_version = "1.2.3" %}
{% set ldas_tools_diskcacheapi_version = "2.7.2" %}
{% set ldas_tools_ldasgen_swig_version = "2.6.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: c49f442be35dea879902313a67fea08f5135252f0576eb2b04a9e9ba0dd94634

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [unix]
    - pkg-config  # [unix]
    - swig >=3.0.7
  host:
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - ldas-tools-diskcacheapi >={{ ldas_tools_diskcacheapi_version }}
  run:
    - ldas-tools-diskcacheapi >={{ ldas_tools_diskcacheapi_version }}

test:
  commands:
    - test -f ${PREFIX}/include/diskcacheAPI/diskCache.i  # [unix]

outputs:
  - name: ldas-tools-diskcacheapi-swig

  - name: python-ldas-tools-diskcacheapi
    script: build-python.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake >=3.20
        - make  # [unix]
        - pkg-config  # [unix]
        - swig >=3.0.7
      host:
        - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
        - {{ pin_subpackage('ldas-tools-diskcacheapi-swig', exact=True) }}
        - python
        - python-ldas-tools-ldasgen >={{ ldas_tools_ldasgen_swig_version }}
      run:
        - python
        - python-ldas-tools-al
        - {{ pin_subpackage('ldas-tools-diskcacheapi-swig', exact=True) }}
        - python-ldas-tools-ldasgen >={{ ldas_tools_ldasgen_swig_version }}
    test:
      imports:
        - LDAStools.diskCache
    about:
      home: https://wiki.ligo.org/Computing/LDASTools
      dev_url: https://git.ligo.org/ldastools/LDAS_Tools.git
      doc_url: https://computing.docs.ligo.org/ldastools/LDAS_Tools/ldas-tools-diskcacheAPI/
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: Python bindings for the LDAS Tools disk cache library

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools.git
  doc_url: https://computing.docs.ligo.org/ldastools/LDAS_Tools/ldas-tools-diskcacheAPI/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: SWIG interface for the LDAS Tools disk cache library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
