travis:
  secure:
    BINSTAR_TOKEN: OfImerJA2srzPZkrogI0YobHDrAZ5NveLlf8PKr8cllXSe1wiYfjMqeeOBiLwNciYRdY4erbSx6zOBjBctat3TeI/RQ14t9u/XTtJmL3V/PkDYriXOV17gSD9Ezu3Ky3WQ7DMtfFppVyNDcYSnNq5DBr3gOi7xBoAf/onyQTwXX27xijFyUohbH6f+r3DqMBP3etS1YLwkoF15AOlgevqW/+6IFtVywnphEl86jxDAHpXFBR8JHrFKXB4wIQvQAbmQSxnSBQ3CTTp+x+ryYfvF9EaMhLYEUrPETDfllQZMzRz6Cf42k6Azsri3k2ZjwBEiamnwLbNmtWfYS1TAnJgUIoL+0w4gdecu1lSlkAtCXI27sjQzfmYASHluUttOE7z9gsBYH0a/7bjYYnlgs+2kEkT/8e3jR+edfr1Sovb63iP2qr60NIHMkwPF9bUBdL2YfjGcwAPtiZ3e4rq12dtm0YCUPhbMK9coOD+n+TCSg+C+R67jBuF0/b/RjfhBToEcNYi5KBygRtQ7djuFRYjgzNAX21EOtsud9pbLs/j1Z+o6ehhn3AbA0cx26tOJUsX5EwQxuyA3RpAiW7w25/5IR/y6cNR+UZQLajZqQe3vCA4uB1owlBJH5bMxXP9f0V5Pjm9Jf4+Qacw+ZAPVR+LLXp4Sf1N4FRcmHxHudfMcg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
